## 30-07-2025

Introduction to NUmpy


In [ ]:
#WHat is Numpy?
# It is a core library for scientific computing in python
# The central on=bject in Numpy is "Numpy array's"
# What is array string?
# High performance mukti dimensional objects which is desgined sepcially for mathamatical operations

In [ ]:
#How many tyeps of arrays
#Three types:
#1D array:- An array with specific rows (axis =0) and no column
#2D array:- An array both rows and columns is known as 2D array
#3D array:- Multidimensional array's

In [ ]:
# What are all use cases and mathamatical operations achived by using Numpy?
'''
1.Dot product/Inner product
2.Matrix mutliplication
3.solving the linear systems
4.Inverse
5.
6.element wise matrix multiplication
7.
8.statistics


# Installing Numpy

In [ ]:
pip install Numpy

In [ ]:
import numpy as np
np.__version__


'2.0.2'

The central object in numpy as Numpy Array

TypeError: array() takes from 1 to 2 positional arguments but 5 were given

In [ ]:
#How can we create an array?
#array's can be created from existing data
a =np.array([1,2,3,4,5])
print(a)
# check the space ofabove array 'a'
a.shape
# fine the dimesnion of the above array
a.ndim
# The number of elemnts in the given array
a.size
# find the size of bytes occupied by each elemnt in above array 'a"
a.itemsize
# find the data type of element in above array
a.dtype

[1 2 3 4 5]


dtype('int64')

# External methods in Numpy

In [ ]:
# access the above element in the array
b = np.array([1,2,3])
#print 2 from the above array
print(b[1])
#reverse the entire string
print(b[::-1])

2
[3 2 1]


In [ ]:
# above array replace the '3' with '5'
b[2] = 5
print(b)




[1 2 5]


In [ ]:
#Numpy:- ordered, immutable and allows duplicates

Element wise math opeartion

In [ ]:
c = np.array([2,0,3])
print(b+c)
# Note:- when applying athemtic operator on two array's. The array has to be in same length
# what is vector addition?
# wheb we apply addition on array's of same length or size we call it as vector addition

[3 2 8]


In [ ]:
b = np.array([5,6,7])
# find the sum of above array
print(b.sum())
# find the minimum element in the above array
print(b.min())
# Maximum element
print(b.max())

18
5
7


# Array's VS List

In [ ]:
l = [1,2,3]
# create an array from the above list
a = np.array([])
# add the 4 into above list
l.append(4)
print(l)

[1, 2, 3, 4]


In [ ]:
#add the new item to the array d
d.append(4)
print(d)
# we cannot add and remove items from the array's

In [ ]:
# How can we add items into array?
# by creating the "New array"
a1 = d +np.array([6])
print(a1)

NameError: name 'd' is not defined

# 31-07-2025

In [ ]:
import numpy as np


In [ ]:
# create an array from
s1 = {1,2,3,4,5}
a = np.array(s1)
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
t1 = (1,2,3,4,5)
b = np.array(t1)
print(type(b))

<class 'numpy.ndarray'>


# 2D- Array

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
# find the no of rows and colms
print(a.shape)
# find the total dimensionality in the array
print(a.ndim)
# find the total elements in the array
print()
# find the data type of an array
print(a.dtype)
print(a.itemsize)

[[1 2 3]
 [4 5 6]]
(2, 3)
2

int64
8


In [ ]:
a = np.array([[1,2,3],[4,5,6]])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
# How can we access the element from array
# print the entire 1st row
# syntax:- array[row_index,col_index]
print(a[0])
print(a[1])
print(a[1,1])
print(a[0,2])

[1 2 3]
[4 5 6]
5
3


In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(a[:,0])
# print the 3rd column values
print(a[:,2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[1 5 9]
[ 3  7 11]


In [ ]:
# access only 10,11,12
print(a[2,1:4])
#print 8 and 12
print(a[1:3,3])
#print only 2 and 6
print(a[0:2,1])

[10 11 12]
[ 8 12]
[2 6]


In [ ]:
b = a[:,0]
for i in b:
  print(i)

1
5
9


**Transpose**

In [ ]:
a =np.array([[1,2,3],[4,5,6]])
print(a)
print(a.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


**Matrix multiplication**-->Dot product

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[5,6]])
# apply dot product on above arrays
c = np.dot(a,b)
print(c)
print(a@b)# one more method

[[13 16]
 [29 36]]
[[13 16]
 [29 36]]


**Inverse**

In [ ]:
a = np.array([[1,2],[3,4]])
d = np.linalg.inv(a)
print(d)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Diagonal**

In [ ]:
a = np.diag(a)
print(a)

[1 4]


In [ ]:
# Note:- Diagonal on vectors return a matrix
c = np.diag([1,2,3])
print(c)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


**Boolean indexing**

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# check the numbers which is more than 2 and print True if more than 2 else print false
l = [1,2,3,4,5,6]
for i in l:
  if i>2:
    print(True)
  else:
    print(False)

False
False
True
True
True
True


In [ ]:
print(a>2)

[[False False]
 [ True  True]
 [ True  True]]


In [ ]:
#print the numbers
print(a[a>2])

[3 4 5 6]


In [ ]:
l = [1,2,3,4,5,6]
print(l*2)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a*2)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [ ]:
# np.where(logic,True,False)
b = np.array([[1,2],[3,4],[5,6]])
# print the numbers grether than 2 and less than numbers print in as a -1
c = np.where(b>2,a,-1)
print(c)


[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [ ]:
# compute the indexes where the condition is True
c = np.array([12,32,45,65,43,66,78])
# get the index poistion of even numbers
even = np.argwhere(c%2==0).flatten()
print(even)

[0 1 5 6]


In [ ]:
even2 = np.argwhere(a%2==0)
print(even2)

[[0 1]
 [1 1]
 [2 1]]


In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
even2 = np.argwhere(a%2==0)
e_ven =a[even2]
print(e_ven)

[[[1 2]
  [3 4]]

 [[3 4]
  [3 4]]

 [[5 6]
  [3 4]]]
